### ISSUE TITLE
Different UI

### ISSUE THREAD

**Issue by etet100** [Clon1998/mobileraker#160]
Have you thought about going in the direction of interfaces used in touch screens of printers? I'm talking about simple interfaces with large, easily touchable buttons, without scrolled lists and other typically web-based solutions. For example something like this?
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware#menus
https://klipperscreen.readthedocs.io/en/latest/Panels/

**Comment by Clon1998** [comment]
Hey,
sorry I didn't comment on this yet.
No so far I did not think about a different or even adaptive UI for different screen sizes. For some Widgets I already did that but for others I didn't. In general the app is currently mainly optimized for phone screens in portrait mode.

I will reopen this issue, since I feel like adding a "Printer screen" mode could be a great idea for people to recycle old android phones for printer screens.
