### ISSUE TITLE
First setup Errors

### ISSUE THREAD

**Issue by LintCritter** [Clon1998/mobileraker#202]
This is my first time trying to use Mobilraker. Its probably something I forgot to configure but just in case I thought i'd try here since the app mentions it. 

![Screenshot_20230726-211557.png](https://github.com/Clon1998/mobileraker/assets/119704905/affa4636-a8bc-48f1-a16a-10f04b26864b)

**Comment by Clon1998** [comment]
Hey,
thanks for bringing that up.
I just double checked the documentation of Klipper and it seems like I did a small oopsie here. I thought the display_status is always available. Bur according to the documentation it is only available if a display was configured.

Therefore my app currently does not work for you since you don't have a display configured.

I will fix that issue hopefully today and can push a hotfix that should be available by Friday hopefully.
