### ISSUE TITLE
Sonic pad notification 

### ISSUE THREAD

**Issue by Piotrek912** [Clon1998/mobileraker#272]
No notifications from Sonic pad 

I was thinking, is it possibile to have notification from the app, without installing anything on the Sonic Pad/klipper instance?

There is visible status of the printer in the app- printing/idle

So maybe app could send notification when this status change? App could work in background and monitor it?

**Comment by Clon1998** [comment]
Hey,
sadly this is not possible due to the Power Saving policies of the OS on Android and especially IOS.
The OS basically kills the notification service after 10min or allows it to run once or twice per hour.

I used this approach initially but it was way to unreliable compared to the current approach.
