### ISSUE TITLE
When the klipper is mapped to a non-80 port, the camera automatically references the 80 port prefix.

### ISSUE THREAD

**Issue by alexands** [Clon1998/mobileraker#289]
### Description
When the klipper is mapped to a non-80 port, the camera automatically references the 80 port prefix.

### Steps to Reproduce
1. Add a printer with domain names that use a non-80 port
2. See the error.

### Expected Behavior
Maybe fix this on the next version?

### Screenshots
![微信图片_20231127145333](https://github.com/Clon1998/mobileraker/assets/30210643/f248ed7d-05da-4378-987e-c82f3fe82eac)
![微信图片_20231127145242](https://github.com/Clon1998/mobileraker/assets/30210643/3991c57e-01d9-4ea3-9a33-244cd759b94d)

### Version Information

- Device-OS (Android/iOS): Android
- Mobileraker: 2.6.7
- Klipper: v0.12.0-10-gea2f6bc0
- Moonraker: v0.8.0-204-gfb15b2a3

#### Checklist
To help us diagnose the issue, please ensure you've completed the following steps:
- [√] Provided a clear bug description.
- [√]  Listed detailed steps to reproduce the issue.
- [√]  Described the expected behavior.
- [√]  Included the Mobileraker version you are using.
- [×] Attached Mobileraker's debug log files.
- [√]  Specified the version numbers of Klipper and Moonraker if applicable.

**Comment by Clon1998** [comment]
Hey,
This is an expected behavior. Most users don't bother using a custom port for the webserver/cam even if they change the moonraker ports. Therefore, the app always uses port `80` rather than the moonraker port for relative cam-URLs.
If you need to use a custom port for any webcam, you will need to use an absolute cam-URL that includes the port.

E.g., if your cam is running on port `90`, you will need to adjust the cam-URL to: `http://<printer-ip>:90/webcam/?<query-params>`.
