### ISSUE TITLE
Layer Information in Push is mixed in multi-part prints

### ISSUE THREAD

**Issue by SirUli** [Clon1998/mobileraker#291]
### Description
When running a multi-part print (e.g. 3 parts, printed one after another), the displayed "current layer" is the one of the current model but not the overall one

### Steps to Reproduce
1. Slice multiple objects **which print one after another**
2. Enable regular notifications (e.g. every 25%)

### Expected Behavior
Either display the total current layer or display the layer of the current model

### Screenshots
![layer](https://github.com/Clon1998/mobileraker/assets/151354/e40a911c-c5ac-4d9f-9a67-e62c229eaadd)

### Version Information

- Device-OS (Android/iOS): iOS
- Mobileraker: 2.6.7-340
- Klipper: v0.12.0-8-g187cc2f1
- Moonraker: v0.8.0-204-gfb15b2a3

### Additional Context
I'm running the lifetime supporter version - not sure if that makes a difference.

---

#### Checklist
To help us diagnose the issue, please ensure you've completed the following steps:
- [X] Provided a clear bug description.
- [X] Listed detailed steps to reproduce the issue.
- [X] Described the expected behavior.
- [X] Included the Mobileraker version you are using.
- [ ] Attached Mobileraker's debug log files.
- [X] Specified the version numbers of Klipper and Moonraker if applicable.

I didn't attach a debug log file as the entire notification happens without me opening mobileraker in the first place. I believe it is more a display issue than an actual issue ;-)

**Comment by Clon1998** [comment]
Hey,
the current layer will always reflect the physical layer and not the current layer of the file. This is because the current layer is calculated based on the current Z-pos of the print head.

This is rather a niche use case, and I don't know if it is even possible to get the current file layer. Therefore, I will close this issue as won't fix.

If you need layer-specific notifications, I suggest you add some custom M117/Macro-based [MR notifications](https://github.com/Clon1998/mobileraker_companion/blob/main/docs/Custom_Notifications.md) directly in the slicer.
