### ISSUE TITLE
Printer unreachable on printer drop down list

### ISSUE THREAD

**Issue by wikolii** [Clon1998/mobileraker#375]
### Description
I recently paid the subscription to be able to add more printers.
I found that in my case there is no way to select the last printer on the list 

### Steps to Reproduce
1. Go to any printer specific page (dashboard, console, etc)
2. Click on the printer name on the top of the screen
3. Scroll down to the last printer
4. See the error. It can't be selected.

### Expected Behavior
Sleect the printer and show it's content

### Screenshots
![image](https://github.com/Clon1998/mobileraker/assets/14824297/2130117d-74d8-4fef-a901-9a39b0483ee4)
### Version Information

- Device-OS (Android/iOS): iOS app v2.6.20-486
- Mobileraker: v0.4.0-63-gea7277ee
- Klipper: v0.12.0-229-g589bd64c
- Moonraker: v0.8.0-379-g346a3d7c

### Additional Context
Add any other relevant context about the problem here.

---

#### Checklist
To help us diagnose the issue, please ensure you've completed the following steps:
- [x] Provided a clear bug description.
- [x] Listed detailed steps to reproduce the issue.
- [x] Described the expected behavior.
- [x] Included the Mobileraker version you are using.
- [ ] Attached Mobileraker's debug log files.
- [x] Specified the version numbers of Klipper and Moonraker if applicable.

**Comment by Clon1998** [comment]
Hey, thanks for reporting that issue.
I noticed that issue myself about two weeks ago and fixed that in f7c963d3dcd03f04b8050aaed2e0a44a9063046c.

If you want, you can join the [TestFlight](https://testflight.apple.com/join/h9JwuyR0) version, which already contains the fix for this issue alongside some other stuff ([Dev Changelog](https://github.com/Clon1998/mobileraker/blob/dev/docs/changelog.md)).

**Comment by wikolii** [comment]
Thanks, loving these new updates
