### ISSUE TITLE
config apk

### ISSUE THREAD

**Issue by Furbein22** [Clon1998/mobileraker#56]
hi i wanted to know if there is a need for a configuration for the apk or app win

**Comment by Furbein22** [comment]
I wanted to know how to connect from the apk to the printer

**Comment by Clon1998** [comment]
Ahh I've got you.
The process should be rather simple.
By default if no printer is added you should see a screen asking you to add a printer.
If that's not the case open the sidebar/menu and press on manage printers -> Add new printer.

![image](https://user-images.githubusercontent.com/10357775/173373516-a31965d1-fbbf-42d7-9605-150eac7f026c.png)

Afterwards you will be directed to the add printer screen.
Enter all the information and press "Test" in order to confirm your printer is working. If it works save it and the app should connect to your printer.

However be sure that your printer is running Klipper with moonraker installed and that your mobile device is in the same network as the printer you are trying to connect!

If you need any more help don't hesitate to comment on this post.

**Comment by Furbein22** [comment]
does it only work in wifi or even cellular network?

**Comment by Clon1998** [comment]
> does it only work in wifi or even cellular network?
> 
> 

Currently most features only work locally.
However, notifications (Priner status, print progress) can be received trough cellular.
However there are a lot of greate tutorial on how to safely connect to your printer using a VPN.
If you're using a VPN the app will also work!

**Comment by Furbein22** [comment]
in fact in wifi it works with the cellular network no, I will try to use a VPN ..
thank you all
